baseURL = "/"
languageCode = "en-us"
title = "Untangled"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Creative Coding"
    url = "/about/creative-coding/"
    weight = 3

[[menu.main]]
    name = "What do I need to know?"
    url = "/about/what-do-i-need-to-know/"
    weight = 4

[[menu.main]]
    name = "Apply"
    url = "/about/apply/"
    weight = 5
[params]
  google_analytics_id=""
  homepage_button_link = '/about'
  homepage_button_text = 'Tell me more'
  homepage_intro = 'A week of experimenting, designing and making with code'
  homepage_image = ''

  [params.homepage_meta_tags]
    meta_description = "Untangled is a week of experimenting, designing and making with code"
    meta_og_title = "Untangled"
    meta_og_type = "website"
    meta_og_url = "/images/screenshot.png"
    meta_og_image = "/images/screenshot.png"
    meta_og_description = "A week of experimenting, designing and making with code"
    meta_twitter_card = "summary"
    meta_twitter_site = "@neontribe"
    meta_twitter_creator = "@neontribe"

  [params.logo]
      mobile = "/images/neontribe-logo-mobile.svg"
      standard  = "/images/neontribe-logo.svg"
