baseURL = "www.untangled.org.uk"
languageCode = "en-us"
title = "Untangled"
themesDir = "../.."
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Untangled is a week of experimenting, designing and making with code for 13-18 year olds from 5th - 9th August 2019.'
  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Untangled is a week of experimenting, designing and making with code for 13-18 year olds from 5th - 9th August 2019."
    meta_og_title = "Untangled"
    meta_og_type = "website"
    meta_og_url = "https://untangled.org.uk"
    meta_og_image = "themes/hugo-whisper-theme/static/images/screenshot.png"
    meta_og_description = "Untangled is a week of experimenting, designing and making with code for 13-18 year olds from 5th - 9th August 2019."
    meta_twitter_card = "summary"
    meta_twitter_site = "@neontribe"
    meta_twitter_creator = "@neontribe

  [params.logo]
      mobile = "themes/hugo-whisper-theme/static/images/neontribe-logo.svg"
      standard  = "themes/hugo-whisper-theme/static/images/neontribe-logo.svg"
